# Generated by Django 2.2.16 on 2022-12-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_genretitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
